project:
  type: website
  output-dir: docs
  
website:
  title: "mathfest2023_score"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

