---
title: "About"
---

This site contains the outline and links for the _Building a SCORE Module to Teach with Sports Data_ breakout session at 2023 USCOTS.

## Session Details

Friday 9:30 – 10:45 AM

## Presenters

Ivan Ramler, Michael Schuckers, and Robin Lock
St. Lawrence University

## Session Description

SCORE with Data is an NSF-funded project that seeks to build a national network to develop and share high quality materials for using Sports Content for Outreach, Research, and Education in statistics and data science. The SCORE network includes both statistics/data science educators, data professionals from sports teams and sports personalities to guide and review the module development process. A key component of this endeavor is to create a repository of teaching modules that connect interesting sports-related questions with appropriate datasets for classroom use. This includes finding appropriate data and guiding students to produce analyses and results that can be communicated to help participants in the sport answer questions of interest. The materials created for each module include students being asked to communicate the analyses that they are undertaking.

This session will introduce participants to the network, engage them with the repository of education modules, review the process for module creation, and discuss how to further engage with and become part of the network. Time permitting, attendees, in small groups, will brainstorm about possible data and questions for further development into a module. As such, it would be helpful for participants to have laptops with internet access for finding data, doing initial analyses, and accessing existing online SCORE modules. Further, interest/experience in one or more sports (as a fan or participant) would be helpful but is not necessary.
